# --- Backend Settings ---
# If "glx" still breaks, change this to "xrender"
backend = "glx";
vsync = true;
use-damage = true;
 detect-client-opacity = true; 
# --- Opacity & Transparency ---
# This makes inactive windows slightly see-through
inactive-opacity = 0.80;
active-opacity = 0.90;
frame-opacity = 1.0;

# Let's keep Neovim/Kitty transparent even when focused if you want:
opacity-rule = [
  "90:class_g = 'Alacritty'",
  #"80:class_g = 'kitty'",
  "100:fullscreen"
];

# --- Fading (Makes i3 feel smoother) ---
fading = true;
fade-delta = 6;
fade-in-step = 0.02;
fade-out-step = 0.02;

# --- Corners & Shadows (Disabled for stability) ---
corner-radius = 12;
shadow = false;

# --- Blur (Simple Kernel Blur) ---
blur-method = "dual_kawase";
blur-background = true;
blur-strength = 3;




# Enable animations
animations = true;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom-out";
animation-for-transient-window = "slide-down";
animation-for-menu-window = "slide-down";
animation-stiffness = 500;
animation-dampening = 20;
animation-window-mass = 0.9;

animation-clamping = false;
animation-for-workspace-switch-in = "slide-left";
animation-for-workspace-switch-out = "slide-right";

opacity-rule = [
  "80:class_g = 'kitty' && focused",
  "60:class_g = 'kitty' && !focused"
];
